### ISSUE TITLE
Sign Up Page

### ISSUE THREAD

**Issue by YuAndyTX** [AndreHrs/Library#4]
**[IMPORTANT]**

- [x] Berikan opsi password visible pada page Sign Up

- [x] Validasi terhadap input, cek username terhadap database

- [x] Required Field

- [x] Tombol Submit Un-Enabled sebelum semua Field telah terisi dengan benar

**Comment by YuAndyTX** [comment]
Karakter '?' biasanya diberikan backcolor atau semacamnya?

**Comment by YuAndyTX** [comment]
**[ENCHANCEMENT]**
Password harus ada minimalnya? seperti minimal 5 karakter, harus terdapat angka, etc.

**Comment by YuAndyTX** [comment]
**[ENCHANCEMENT]**
Berikan

**Comment by AndreHrs** [comment]
Sudah ada validasi dasar tapi belum cek ke database dan tombol di disable

**Comment by YuAndyTX** [comment]
Done
